import Head from "next/head";
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillGithub,
} from "react-icons/ai";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { useState } from "react";
import glassesowl from "../public/glasses-owl.png";
// import resume from "./resume.pdf";
// import code from "../public/code.png";
// import design from "../public/design.png";
// import consulting from "../public/consulting.png";
import computerdynamiccolor from "../public/computer-dynamic-color.png";
import walletdynamicpremium from "../public/wallet-dynamic-premium.png";
import blenderdynamiccolor from "../public/blender-dynamic-color.png";
import Image from "next/image";
import cambiawellbeing from "../public/cambia_wellbeing.png";
import chamberfoundation from "../public/chamber_foundation.png";
import coowncosidebar from "../public/coownco_sidebar.png";
import avedablog from "../public/aveda-blog.png";
import iterationgallery from "../public/iterationgallery.png";
import jubilantsnapshot from "../public/jubilant-snapshot.jpg";
import salmonberry from "../public/salmonberry.png";
// import planet from "../public/planet.png";
// import beakerfamily2 from "../public/beakerfamily2.png";
import gogo3 from "../public/gogo3.png";
// import iterationtote from "../public/iteration-tote.png";
// import croppedscreenshot from "../public/croppedscreenshot.png";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  // Function will execute on click of button
  const onButtonClick = () => {
    // using Java Script method to get PDF file
    fetch("./resume.pdf").then((response) => {
      response.blob().then((blob) => {
        // Creating new object of PDF file
        const fileURL = window.URL.createObjectURL(blob);
        // Setting various property values
        let alink = document.createElement("a");
        alink.href = fileURL;
        alink.download = "./resume.pdf";
        alink.click();
      });
    });
  };

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>New React Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" bg-white px-10 dark:bg-gray-900  md:px-20 lg:px-40">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between dark:text-white">
            <a
              target="_blank"
              href="https://immersiveowl.com/"
              rel="noopener noreferrer"
            >
              <h1 className="font-burtons text-xl">ImmersiveOwl</h1>
            </a>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className=" cursor-pointer text-2xl"
                />
              </li>
              <li>
                <button
                  className="bg-gradient-to-r from-green-400 text- to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8"
                  onClick={onButtonClick}
                >
                  Resume
                </button>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10 py-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium dark:text-teal-400 md:text-6xl">
              Deenie Wallace
            </h2>
            <h3 className="text-2xl py-2 dark:text-white md:text-3xl">
              Web Developer | Creative Technologist
            </h3>
            <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl">
              Inhabiting where code and artistry meet.
            </p>
            <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400">
              <a
                target="_blank"
                href="https://twitter.com/jubilantdeenie"
                rel="noopener noreferrer"
              >
                <AiFillTwitterCircle />
              </a>
              <a
                target="_blank"
                href="https://www.linkedin.com/in/deenie-wallace"
                rel="noopener noreferrer"
              >
                <AiFillLinkedin />
              </a>
              <a
                target="_blank"
                href="https://github.com/jubilantdeenie"
                rel="noopener noreferrer"
              >
                <AiFillGithub />
              </a>
            </div>
            <div className="mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 relative overflow-hidden mt-20 md:h-96 md:w-96">
              <Image
                src={glassesowl}
                rel="preload"
                priority="true"
                layout="fill"
                objectFit="cover"
                alt="owl with glasses logo"
              />
            </div>
          </div>
        </section>
        <section>
          <div>
            <h3 className="text-3xl py-1 dark:text-white ">Services I offer</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              I am passionate about delivering beautiful and user-friendly{" "}
              <span className="text-teal-500"> websites </span> that meet the
              needs of my clients. I work with a variety of platforms and{" "}
              <span className="text-teal-500">eCommerce </span> solutions to
              support enterprise and small business sites.
            </p>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              As a creative technologist, I make{" "}
              <span className="text-teal-500"> 3D art</span> into custom digital
              assets and scenes, for VR and the web, with a focus on object
              modeling and building immersive interactions that delight and
              fascinate.
            </p>
          </div>
          <div className="lg:flex gap-10">
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <Image src={computerdynamiccolor} width={100} height={100} />
              <h3
                className="text-lg font-medium pt-8 pb-2"
                alt="desktop computer icon"
              >
                Web Development
              </h3>
              <p className="py-2">
                Development, testing, and support for new and legacy sites.
              </p>
              <h4 className="py-4 text-teal-400">Tools I Use</h4>
              <p className="text-gray-800 py-1">JavaScript</p>
              <p className="text-gray-800 py-1">WordPress</p>
              <p className="text-gray-800 py-1">Drupal</p>
              <p className="text-gray-800 py-1">Shopify</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10  dark:bg-white flex-1">
              <Image src={walletdynamicpremium} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2  ">e-Commerce</h3>
              <p className="py-2" alt="wallet with cards icon">
                Building efficient and scalable models for your virtual
                storefront.
              </p>
              <h4 className="py-4 text-teal-400">Tools I Use</h4>
              <p className="text-gray-800 py-1">Shopify</p>
              <p className="text-gray-800 py-1">WooCommerce</p>
              <p className="text-gray-800 py-1">Dropshipping</p>
              <p className="text-gray-800 py-1">Print On Demand</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <Image src={blenderdynamiccolor} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2" alt="Blender logo">
                3D Generalist
              </h3>
              <p className="py-2">
                Custom assets, images, and immersive experiences.
              </p>
              <h4 className="py-4 text-teal-400">Tools I Use</h4>
              <p className="text-gray-800 py-1">XR | VR</p>
              <p className="text-gray-800 py-1">Blender 3D</p>
              <p className="text-gray-800 py-1">Unity </p>
              <p className="text-gray-800 py-1">Three JS</p>
            </div>
          </div>
        </section>
        <section className="py-10">
          <div>
            <h3 className="text-3xl py-1 dark:text-white ">
              Site Maintenance and Updates
            </h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              From code driven JavaScript websites to CMS management and updates
              for WordPress and Drupal, my work is powered by my creative
              problem solving and technical ability, enabling me to create
              efficient solutions that bring about long-lasting results.
            </p>
          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-md object-cover"
                width={"100%"}
                height={"60%"}
                layout="responsive"
                src={cambiawellbeing}
                alt="example of drupal work"
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"60%"}
                layout="responsive"
                src={chamberfoundation}
                alt="example of drupal work"
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"60%"}
                layout="responsive"
                src={coowncosidebar}
                alt="example of wordpress work"
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"60%"}
                layout="responsive"
                src={avedablog}
                alt="example of drupal work"
              />
            </div>
          </div>
        </section>
        <section className="py-10">
          <div>
            <h3 className="text-3xl py-1 dark:text-white ">
              Shopify & WooCommerce
            </h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              My skills extend to designing, building, and supporting eCommerce
              websites. I am adept at theme conversion, API configuration, and
              print on demand product creation; helping to bring the site
              concept to life with a comprehensive user experience.
            </p>
          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-md object-cover"
                width={"100%"}
                height={"60%"}
                layout="responsive"
                src={iterationgallery}
                alt="example of shopify ecommerce work"
              />
            </div>
            {/* <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"60%"}
                layout="responsive"
                src={iterationtote}
              />
            </div> */}
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"60%"}
                layout="responsive"
                src={jubilantsnapshot}
                alt="example of wordpress woocommerce work"
              />
            </div>
            {/* <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"60%"}
                layout="responsive"
                src={croppedscreenshot}
              />
            </div> */}
          </div>
        </section>
        <section className="py-10">
          <div>
            <h3 className="text-3xl py-1 dark:text-white ">Blender 3D</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              Combining my background in art and design with technical tools
              allows me to create CG models, textures, and lighting that are
              realistic and polished. I believe that beauty and meaningfulness
              should be at the heart of every experience, whether it’s online or
              in VR.
            </p>
          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"60%"}
                layout="responsive"
                src={gogo3}
                alt="example of Blender 3D text work"
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-md object-cover"
                width={"100%"}
                height={"60%"}
                layout="responsive"
                src={salmonberry}
                alt="example of Blender 3d modeling work"
              />
            </div>
            {/* <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"60%"}
                layout="responsive"
                src={beakerfamily2}
              />
            </div> */}
            {/* <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"60%"}
                layout="responsive"
                src={planet}
              />
            </div> */}
          </div>
        </section>
      </main>
    </div>
  );
}

// This website is made with React and Tailwind CSS!
// Thank you to developedbyed for their youTube video that inspired this site.
// "Build a React Portfolio Website With Tailwind Tutorial"  https://youtu.be/k-Pi5ZMxHWY
